### ISSUE TITLE
Running the script doesn't do anything

### ISSUE THREAD

**Issue by justifun** [Toolchefs/motionPath#2]
Running the python script in maya doesn't do anything.  The tool doesn't load.  Is there any trick to launching it?

**Comment by danielefederico** [comment]
Hello,
that is because you need to compile the plugin itself first. 
If you don't know how, please search help amoung your fellow tech colleagues.
Thanks

**Comment by junyu001** [comment]
This python file only defines functions, not calls them, and the python file can be run only if it is imported as a module; execute the run function inside the python file. We also need to compile the open source c++ file, which was able to run successfully on Maya2018
